2024-08-15 09:30:18,994 ERROR: Error occurred: username email and passwod are compulsory [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 09:30:26,567 ERROR: Error occurred: username email and passwod are compulsory [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 09:30:39,829 ERROR: Error occurred: username email and passwod are compulsory [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 09:31:34,687 ERROR: Error occurred: username email and passwod are compulsory [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 09:34:32,201 ERROR: Error occurred: 'User' object has no attribute 'user_id' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 09:34:52,831 ERROR: Error occurred: Unauthorized [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 09:35:25,360 ERROR: Error occurred: details not found [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:24:37,516 ERROR: Error occurred: 400 Bad Request: Did not attempt to load JSON data because the request Content-Type was not 'application/json'. [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:25:01,752 ERROR: Error occurred: The phone number is invalid (caused by SendCodeRequest) [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:27:19,888 ERROR: Error occurred: please provide bot_name and bot_username [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:27:38,118 ERROR: Error occurred: 'NoneType' object has no attribute 'phone' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:28:20,010 ERROR: Error occurred: 'NoneType' object has no attribute 'phone' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:28:39,976 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:29:23,589 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:29:49,189 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:30:45,540 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:31:59,406 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:38:36,571 ERROR: Error occurred: get() missing 1 required positional argument: 'ident' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 10:39:26,520 ERROR: Error occurred: get() missing 1 required positional argument: 'ident' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 11:54:48,771 ERROR: Error occurred: 'str' object has no attribute 'get' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:24:22,849 ERROR: Error occurred: Not a valid string [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:24:52,376 ERROR: Error occurred: Not a valid string [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:25:08,538 ERROR: Error occurred: Not a valid string [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:25:26,463 ERROR: Error occurred: Not a valid string [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:25:55,274 ERROR: Error occurred: Not a valid string [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:26:29,150 ERROR: Error occurred: database is locked [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:27:18,498 ERROR: Error occurred: Not a valid string [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:27:57,902 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:28:08,042 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:28:45,448 ERROR: Error occurred: 'int' object is not subscriptable [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:29:01,704 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:30:26,570 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:33:55,244 ERROR: Error occurred: No Telegram session found [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-15 12:49:18,547 ERROR: Error occurred: The phone number is invalid (caused by SendCodeRequest) [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 09:44:17,371 ERROR: Error occurred: The phone number is invalid (caused by SendCodeRequest) [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 09:44:48,414 ERROR: Error occurred: The phone number is invalid (caused by SendCodeRequest) [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 09:48:36,407 ERROR: Error occurred: no phone found [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 09:53:09,602 ERROR: Error occurred: The confirmation code has expired (caused by SignInRequest) [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 12:01:04,347 ERROR: Error occurred: no telegram session [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 12:01:14,109 ERROR: Error occurred: database is locked [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 13:34:27,126 ERROR: Error occurred: 'CreateBot' object has no attribute 'webhook_url' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 13:34:34,662 ERROR: Error occurred: 'CreateBot' object has no attribute 'webhook_url' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 13:34:39,528 ERROR: Error occurred: 'CreateBot' object has no attribute 'webhook_url' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 13:34:40,146 ERROR: Error occurred: 'CreateBot' object has no attribute 'webhook_url' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 13:35:50,256 ERROR: Error occurred: 'CreateBot' object has no attribute 'webhook_url' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 13:36:24,226 ERROR: Error occurred: 'CreateBot' object has no attribute 'webhook_url' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-16 13:55:29,661 ERROR: Error occurred: 'name' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:07:17,765 ERROR: Error occurred: bot not excisting [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:07:32,144 ERROR: Error occurred: There is no current event loop in thread 'Thread-7'. [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:08:32,257 ERROR: Error occurred: There is no current event loop in thread 'Thread-2'. [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:09:11,489 ERROR: Error occurred: There is no current event loop in thread 'Thread-2'. [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:09:43,487 ERROR: Error occurred: There is no current event loop in thread 'Thread-2'. [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:11:08,790 ERROR: Error occurred: There is no current event loop in thread 'Thread-2'. [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:12:32,504 ERROR: Error occurred: No such event in this bot [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:12:38,973 ERROR: Error occurred: bot not existing [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:12:50,332 ERROR: Error occurred: No such event in this bot [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:12:52,385 ERROR: Error occurred: No such event in this bot [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:13:16,713 ERROR: Error occurred: No such event in this bot [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:14:39,218 ERROR: Error occurred: This Application was not initialized via `Application.initialize`! [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:23:09,398 ERROR: Error occurred: 'int' object has no attribute 'get' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
2024-08-19 13:24:30,460 ERROR: Error occurred: module 'telegram.ext.filters' has no attribute 'regex' [in /Users/adilanwar/Documents/tecpaybot/app/service/common/session_factory.py:71]
